version: '3.1'
services:
  web:
    build:
      context: ./
    volumes:
      - ./app:/var/www/app
      - ./web:/var/www/html
      - ./vendor:/var/www/vendor
    ports:
      - "80:80"
    environment:
      ALLOW_TEST_LOGIN: 1
    depends_on:
      - db

  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rippler
